name: Commit Check
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  commit-check:
    name: Commit Check
    runs-on: ubuntu-24.04
    env:
      PR_AUTHOR: ${{ github.event.pull_request.user.login }}
    steps:
    - name: Get PR Commits
      id: 'get-pr-commits'
      uses: tim-actions/get-pr-commits@c64db31d359214d244884dd68f971a110b29ab83 # v1.2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        # Filter out revert commits
        # The format of a revert commit is as follows:
        #
        # Revert "<original-subject-line>"
        #
        # The format of a re-re-vert commit as follows:
        #
        # Reapply "<original-subject-line>"
        filter_out_pattern: '^Revert "|^Reapply "'

    - name: DCO Check
      uses: tim-actions/dco@2fd0504dc0d27b33f542867c300c60840c6dcb20 # master (2020-04-28)
      with:
        commits: ${{ steps.get-pr-commits.outputs.commits }}
    